{
  pkgs,
  ...
}:

let
  # Read the per-device username from ../local.nix (gitignored; generated by
  # ./setup.sh) so the desktop image bakes the right user's home dir.
  local = if builtins.pathExists ../local.nix then import ../local.nix else {};
  userName = local.userName or "ryuzaki";

  # Starter files are copied to the user's home on first activation only
  # (`cp -n`), so user edits are never overwritten afterwards.
  seedUserConfig = {
    text = ''
      mkdir -p /home/${userName}/.config/noctalia
      mkdir -p /home/${userName}/.config/hypr
      cp -n ${../modules/noctalia.toml} /home/${userName}/.config/noctalia/config.toml || true
      cp -n ${../modules/hyprland.conf} /home/${userName}/.config/hypr/hyprland.conf || true
      # chown the parent .config too (and everything under it): `mkdir -p` above
      # creates it as root, which would stop the user from writing any new config.
      chown -R ${userName}:users /home/${userName}/.config
    '';
    deps = [ ];
  };
in
{
  # ---------------------------------------------------------------------------
  # Hyprland compositor, wrapped by UWSM so it starts graphical-session.target
  # (the target the Noctalia shell runs under).
  # ---------------------------------------------------------------------------
  programs.hyprland = {
    enable = true;
    withUWSM = true;
  };

  # ---------------------------------------------------------------------------
  # Noctalia v5: sleek Wayland desktop shell (bar, launcher, notifications...).
  # Available in this nixpkgs; runs as a systemd user service bound to the
  # Hyprland session.
  # ---------------------------------------------------------------------------
  programs.noctalia = {
    enable = true;
    systemd = {
      enable = true;
      target = "graphical-session.target";
    };
    recommendedServices.enable = true;
  };

  # ---------------------------------------------------------------------------
  # Autologin: greetd drops straight into the Hyprland + Noctalia desktop.
  # ---------------------------------------------------------------------------
  services.greetd = {
    enable = true;
    settings = {
      default_session = {
        command = "${pkgs.uwsm}/bin/uwsm start hyprland";
        user = userName;
      };
    };
  };

  # Seed starter dotfiles on first boot.
  system.activationScripts.seed-user-config = seedUserConfig;

environment.systemPackages = with pkgs; [
    foot
    firefox
    wl-clipboard
    brightnessctl
  ];

  # Let the desktop user control brightness (RP1 backlight) and access DRM/input
  # devices for the compositor.
  users.users.${userName}.extraGroups = [ "video" "input" ];
}