{
  config,
  pkgs,
  lib,
  ...
}:

let
  # The flake source (this repo), filtered so we only bake code/docs onto the
  # device - never build artifacts, git metadata or generated images.
  flakeSource = builtins.path {
    path = ./.;
    name = "rpi-nixos-flake";
    filter = path: type:
      let base = baseNameOf path;
      in base != ".git" && base != "result" && base != "images";
  };

  # Per-device personal config + secrets. Generated by ./setup.sh (or copied
  # from the *.example templates). Both are gitignored. Since ../local.nix and
  # ../secrets.nix live next to this file, import them with ./ paths.
  local = if builtins.pathExists ./local.nix then import ./local.nix else {};
  secrets = if builtins.pathExists ./secrets.nix then import ./secrets.nix else {};
in
{
  networking.hostName = local.hostName or "ryuzakipi";

  # ---------------------------------------------------------------------------
  # User accounts
  # ---------------------------------------------------------------------------
  users.users.${local.userName or "ryuzaki"} = {
    isNormalUser = true;
    extraGroups = [
      "wheel"
      "video"
    ];
    # One-time bootstrap password. Run `passwd` on first login to replace it.
    initialPassword = secrets.userPassword or "changeme";
    openssh.authorizedKeys.keys =
      lib.optionals (local.sshKey or null != null && local.sshKey != "") [ local.sshKey ];
  };

  users.users.root.openssh.authorizedKeys.keys =
    lib.optionals (local.sshKey or null != null && local.sshKey != "") [ local.sshKey ];

  # The nvmd/nixpkgs installer profile declares a default `nixos` user account
  # (normal user, wheel + networkmanager + video, empty password). Neutralize it
  # to an inert system user (nologin shell, no groups, no home, no keys) so the
  # ONLY usable account on device is the per-device user from local.nix above
  # (chosen via ./setup.sh) — no stray default user with sudo access survives.
  users.users.nixos = lib.mkForce {
    isSystemUser = true;
    group = "nogroup";
    home = "/var/empty";
    createHome = false;
    shell = "/run/current-system/sw/bin/nologin";
    hashedPassword = lib.mkForce null;
    openssh.authorizedKeys.keys = lib.mkForce [ ];
  };

  # ---------------------------------------------------------------------------
  # SSH
  # ---------------------------------------------------------------------------
  services.openssh = {
    enable = true;
    settings = {
      PasswordAuthentication = false;
      PermitRootLogin = "prohibit-password";
    };
  };

  # mDNS: reachable at ryuzakipi.local
  services.avahi.enable = true;

  # ---------------------------------------------------------------------------
  # Wi-Fi via NetworkManager.
  # The nvmd installer profile enables NetworkManager, so Wi-Fi is configured
  # declaratively as an NM connection profile rather than with wpa_supplicant.
  # To connect to the network interactively later: `nmcli device wifi connect`.
  # ---------------------------------------------------------------------------
  networking.networkmanager = {
    enable = true;
    ensureProfiles.profiles =
      if (local.wifi or {}).ssid or "" == "" then
        { }
      else
        {
          "${local.wifi.ssid}" = {
            connection = {
              id = local.wifi.ssid;
              type = "wifi";
              autoconnect = true;
            };
            wifi = {
              ssid = local.wifi.ssid;
              mode = "infrastructure";
            };
            wifi-security = {
              key-mgmt = "wpa-psk";
              psk = secrets.wifiPsk or "changeme";
            };
            ipv4 = { method = "auto"; };
            ipv6 = { method = "auto"; };
          };
        };
  };

  # ---------------------------------------------------------------------------
  # Extra packages
  # ---------------------------------------------------------------------------
  environment.systemPackages = with pkgs; [
    git
    htop
    tree
    vim
  ];

  # ZFS is not used; silence the sd-image warning about forceImportRoot.
  boot.zfs.forceImportRoot = false;

  # ---------------------------------------------------------------------------
  # Bake the flake into /etc/nixos so the device can be rebuilt on-device:
  #   sudo nixos-rebuild switch --flake /etc/nixos#rpi5
  # ---------------------------------------------------------------------------
  system.activationScripts.etc-nixos = {
    text = ''
      mkdir -p /etc/nixos
      cp -rLf ${flakeSource}/. /etc/nixos/
    '';
    deps = [ ];
  };

  system.stateVersion = "26.05";
}
